---
###########################################
#            BACKUP A GIT-LAB             # 
# !!!PRECAUCIÃ“N!!! NO MODIFICAR EL CODIGO # 
###########################################

# BACKUP SHOW IP INTERFACE BRIEF #
- name: Backup GITLAB "show ip interface brief"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "ip-int-br-"
        git_ruta: "backup-show_ip_int_br"
        mensaje_commit: "backup show ip interface brief" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".txt"
- name: Push GITLAB "show ip interface brief"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab

# BACKUP SHOW RUN #
- name: Backup GITLAB "show run"
  hosts: all 
  gather_facts: no
  tasks:   
    - include_role:
        name: gitlab
      vars: 
        git_prefijo: "run-"
        git_ruta: "backup-show_run"
        mensaje_commit: "backup show run" 
        nombre_equipo: "{{ inventory_hostname }}"
        extension: ".txt"
- name: Push GITLAB "show run"
  hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: push_gitlab